services:
  postgres:
    image: postgres:17
    container_name: product-api-postgres
    environment:
      POSTGRES_DB: product_api
      POSTGRES_USER: product_user
      POSTGRES_PASSWORD: product_password
    ports:
      - "5432:5432"
    volumes:
      - product-api-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U product_user -d product_api"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8
    container_name: ec-demo-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:1.31
    container_name: ec-demo-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
      - postgres

  rabbitmq:
    image: rabbitmq:4-management
    container_name: ec-demo-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  product-api-postgres-data:
  redis-data:
  rabbitmq-data:
