spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product_api
    username: product_user
    password: product_password
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          multiplier: 2
          max-attempts: 3
          max-interval: 5000
opensearch:
  host: localhost
  port: 9200

jwt:
  secret: "this-is-a-local-development-secret-key-for-jwt-authentication"
  expiration-minutes: 60
