spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product_api
    username: product_user
    password: product_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true
